---

- name: clone the github repo {{ role_name}}
  git:
    repo: https://github.com/hbraux/{{ role_name}}.git
    dest: "{{ ansible_env.HOME }}/git/{{ role_name}}"

- name: create the link
  file:
    src: "{{ ansible_env.HOME }}/git/{{ role_name}}/ansible"
    dest: "{{ playbook_dir }}/roles/"
    state: link

- name: run the embedded playbook
  include_tasks: "{{ playbook_dir }}/roles/work-env/setup.yml"

