---

- set_fact:
    repo: "{{ git_path | basename }}"

- set_fact:
    repo_dir: "{{ ansible_env.HOME }}/git/{{ repo }}"

- name: "{{ repo }} : check if {{ repo_dir }} exists"
  stat:
    path: "{{ repo_dir }}"
  delegate_to: localhost
  register: st
    
- name: "{{ repo }} : clone the repo from github"
  git:
    repo: https://github.com/{{ git_path }}.git
    dest: "{{ repo_dir }}"
  delegate_to: localhost
  when: not st.stat.exists

- name: "{{ repo }} : run the project playbook setup.yml"
  include_tasks: "{{ repo_dir }}/setup.yml"


