- name: download version file
  get_url:
    url: https://raw.githubusercontent.com/netdata/binary-packages/master/netdata-latest.gz.run
    dest: /tmp/netdata-version

- name: get version from file 
  shell: cat /tmp/netdata-version
  register: cat_cmd
  changed_when: false

- name: download binary
  get_url:
    url: https://raw.githubusercontent.com/netdata/binary-packages/master/{{ cat_cmd.stdout }}
    dest: /tmp/netdata.gz.run

- name: install netdata
  shell: sh /tmp/netdata.gz.run --accept --quiet
  args:
    creates: /opt/netdata

- name : check port 19999
  wait_for:
    port: 19999

- name: get hostname
  shell: uname -n
  register: hostname_cmd
  changed_when: false

- name: add message to motd
  lineinfile: 
    path: /etc/motd
    regexp: "^netdata .*"
    line: "netdata is running on http://{{ hostname_cmd.stdout}}:19999/"
