---

- name: install python 3.6
  yum:
    name: 'python36'

- name: install pip3
  shell: |
    python3.6 -m ensurepip && /usr/local/bin/pip3 install --upgrade pip
  args:
    creates: /usr/local/bin/pip3

- name: create python3 link
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python3
    state: link

- name: install basic python3 packages
  shell: /usr/local/bin/pip3 install {{ item }}
  args:
    creates: /usr/local/lib/python3.6/site-packages/{{ item }}
  with_items: "{{ python3.packages }}"
 

    
  

