---

- name: install python 3
  yum:
    name: python3

- name: install pip3
  shell: python3 -m ensurepip && pip3 install --upgrade pip

- name: install basic python3 packages
  shell: pip3 install {{ item }}
  args:
    creates: /usr/local/lib/python3.6/site-packages/{{ item }}
  with_items: "{{ python3.packages }}"

