---

- set_fact:
    url: "{{ project_url }}"
  when: project_url | regex_search('^http')

- set_fact: 
    url: https://github.com/{{ project_url }}
  when:  url is not defined
  
- set_fact: 
    repo: "{{ project_url | basename }}"

- set_fact:
    repo_dir: "{{ ansible_env.HOME }}/git/{{ repo }}"


- name: "{{ repo }} : check if {{ repo_dir }} exists"
  stat:
    path: "{{ repo_dir }}"
  delegate_to: localhost
  register: st
    
- name: "{{ repo }} : clone the repo from github"
  git:
    repo: project_url.git
    dest: "{{ repo_dir }}"
  delegate_to: localhost
  when: not st.stat.exists

- name: "{{ repo }} : run the project playbook setup.yml"
  include_tasks: "{{ repo_dir }}/setup.yml"

